Stg 27
OnStageApp/on-stage-app pull request #105
Opened 2024-08-10 16:38 UTC by BeniaminSzilagyi

## Title

## Description

## Screenshots

2024-08-10 20:45 UTC, ToniVinter commented on lib/app/shared/invite_button.dart
> +          if (isConfirm != true)
isConfirm is a boolean, simply write !isConfirm

2024-08-10 20:46 UTC, ToniVinter commented on lib/app/shared/invite_button.dart
> +          if (isConfirm != true)
better start with 

if(isConfirm)
Asset.icons.confirm.svg()
else
....

2024-08-10 20:47 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +            if (isNotificationHasActionButtons)
better naming hasActionButtons

2024-08-10 20:48 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +                            style: Theme.of(context)
context.textTheme, not Theme.of(....)

2024-08-10 20:48 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +                          _buildCircle(context, context.colorScheme.outline.withOpacity(0.2)),
you don't need to send context via params here

2024-08-10 20:48 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +                            style: Theme.of(context)
context.text....

2024-08-10 20:49 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +                            _buildCircle(context, context.colorScheme.error),
don't need context via param

2024-08-10 20:52 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +    this.isNotification = false,
these doesn't have to be send via param, none of them

2024-08-10 20:53 UTC, ToniVinter commented on lib/app/features/notifications/presentation/notification_page.dart
> +  String _getLeftTime(DateTime dateTime) {
we have a eventControllerProvider, all logic & state has to be in there. Look in other examples.

2024-08-10 21:01 UTC, ToniVinter commented on lib/app/features/notifications/presentation/notification_page.dart
> +  String _getLeftTime(DateTime dateTime) {
So, short overview of how this must be done:

We will have an enum, named NotificationTimeFilterEnum ( new, lastWeek, lastMonth as values ) 

We will retrieve from backend 3 different lists:
 - new - List<Notification> unreadNotifications;
 - lastSevenDays -  List<Notification> lastSevenDaysNotifications;
 - lastThirtyDays  -  List<Notification> lastThirtyDaysNotifications;
 
 when all data is loaded we will show all notifications but under these 3 categories.
 We don't have to calculate if the notification is new, or ther stuffs

leftTime can be calculated in the Event class, we don't need any logic in the UI
 
 So, most part of this class has to be refactored

2024-08-10 21:01 UTC, ToniVinter commented on lib/app/features/notifications/presentation/notification_page.dart
> +    final today = DateTime(now.year, now.month, now.day);
read the comment bellow, we do not need these

2024-08-10 21:01 UTC, ToniVinter commented on lib/app/features/notifications/presentation/notification_page.dart
> +          ? SingleChildScrollView(child: _buildBody(notifications, context))
you don't have to send context via params

2024-08-10 21:02 UTC, ToniVinter requested changes
See big comment below

2024-08-21 16:06 UTC, BeniaminSzilagyi commented on lib/app/shared/invite_button.dart
> +          if (isConfirm != true)
if (!isConfirm)

2024-08-21 16:09 UTC, BeniaminSzilagyi commented on lib/app/shared/event_tile.dart
> +                          _buildCircle(context, context.colorScheme.outline.withOpacity(0.2)),
what params?

2024-08-21 16:14 UTC, BeniaminSzilagyi commented on lib/app/shared/event_tile.dart
> +                          _buildCircle(context, context.colorScheme.outline.withOpacity(0.2)),
<img width="190" alt="Screenshot 2024-08-21 at 7 13 31 PM" src="https://github.com/user-attachments/assets/f6720b40-7d81-40c3-b50e-bd85fb81364b">

I am reusing the _buildCircle, between the Hour _buildCircle Date

And before the Title if it's a new notification

2024-08-21 16:15 UTC, BeniaminSzilagyi commented on lib/app/shared/event_tile.dart
> +    this.isNotification = false,
What do you mean?

2024-08-21 16:17 UTC, BeniaminSzilagyi commented on lib/app/features/notifications/presentation/notification_page.dart
> +  String _getLeftTime(DateTime dateTime) {
Yeah, I was thinking that all these will come after BE

new - List unreadNotifications;
lastSevenDays - List lastSevenDaysNotifications;
lastThirtyDays - List lastThirtyDaysNotifications;

I just done right now on the FE to have the UI/UX logic.

What do you want me to proceed further?

2024-08-21 16:18 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +                          _buildCircle(context, context.colorScheme.outline.withOpacity(0.2)),
_buildCircle(context,....)

nu-ti trebuie context in paranteze, daca-l stergi o sa vezi ca o sa stie sa foloseasca contextul din screen

2024-08-21 16:22 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +    this.isNotification = false,
pai o sa avem un obiect, care o sa aiba parametri de genul 

"hasActions":"true"

si de acolo setezi daca are actions, sau daca notificarea ii noua, la fel, o sa fie un field 
"seen": "true"

toti ce trebuie sa faci ii sa trimiti obiectul.

+ nu refolosi event_item pentru notifications, fa un alt widget asemanator cu asta, n-as vrea sa-l incarcam pe asta super mult, nu o sa fim afisam butoanele in lista de eventuri, doar in notificari

2024-08-21 16:22 UTC, ToniVinter commented on lib/app/shared/event_tile.dart
> +    this.isNotification = false,
prin obiect ma refer la Notifcation()

2024-08-21 16:49 UTC, BeniaminSzilagyi commented on lib/app/shared/event_tile.dart
> +    this.isNotification = false,
this Tile is used also in other place and that's why I have added isNotification

2024-08-21 18:49 UTC, ToniVinter commented on lib/app/features/notifications/presentation/notification_page.dart
> +  String _getLeftTime(DateTime dateTime) {
you have to create all the logic.

notification_repository.dart
notification_notifier.dart

same as other examples.

Implement APIs call with retrofit.
getUnreadNotifications()
getLastSevenDaysNotifications()
getLastThirtyDays()

You have to implement these in repo and notifier too. 
Use them in UI by saving their state into NotificationState

2024-08-21 18:50 UTC, ToniVinter commented on lib/app/features/notifications/presentation/notification_page.dart
> +  String _getLeftTime(DateTime dateTime) {
For now just return some dummy, but we have to create these files and methods

2024-08-21 18:50 UTC, ToniVinter commented on lib/app/features/notifications/presentation/notification_page.dart
> +  String _getLeftTime(DateTime dateTime) {
in notifier, instead of calling the repo, call a dummy file

2024-09-05 11:32 UTC, BeniaminSzilagyi commented on lib/app/features/notifications/presentation/notification_page.dart
> +          ? SingleChildScrollView(child: _buildBody(notifications, context))
need the context for the following, we need to pass that param

![Screenshot 2024-09-05 at 2 32 23 PM](https://github.com/user-attachments/assets/4ffff35a-7baf-4469-a95a-b6b1e6f8feed)

2024-09-05 11:33 UTC, BeniaminSzilagyi commented on lib/app/features/notifications/presentation/notification_page.dart
> +    final today = DateTime(now.year, now.month, now.day);
Can we just leave it for the moment util we implement with the BE?

2024-09-05 15:43 UTC, ToniVinter commented on ios/Runner.xcodeproj/xcshareddata/xcschemes/Debug.xcscheme
remove this from commit

2024-09-05 15:45 UTC, ToniVinter commented on lib/app/features/notifications/presentation/notification_page.dart
> +    ref.read(notificationNotifierProvider.notifier).getNotifications();
This will get the notifcation every time something in the screen is modified.
Look for other examples where I handle the data.

Something like this:
`  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      ref.read(songsNotifierProvider.notifier).getSongs(
            isLoadingWithShimmer: true,
          );
    });
    super.initState();
  }`

2024-09-05 15:47 UTC, merged