Stg 163
OnStageApp/on-stage-app pull request #182
Opened 2024-12-04 10:13 UTC by BeniaminSzilagyi

## Title

## Description

## Screenshots

2024-12-04 10:35 UTC, ToniVinter requested changes

2024-12-04 10:35 UTC, ToniVinter commented on ios/Podfile
Nu-i ok sa adaugi permisiuni in Podfile, asta se regenereaza si alea vor disparea..

2024-12-04 10:35 UTC, ToniVinter commented on lib/app/features/user/presentation/widgets/add_photo_modal.dart
> +      debugPrint('Permission not granted. Cannot open photo picker.');
use logger.i , we don't use debugPrint

2024-12-04 10:35 UTC, ToniVinter commented on android/app/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.CAMERA"/>
avem nevoie de camera?

2024-12-04 10:35 UTC, ToniVinter commented on lib/app/features/user/presentation/widgets/add_photo_modal.dart
> +    final status = await Permission.photos.status;
aici ti-ai facut o variabila, o folosesti o singura data.

Cred ca poti sa folosesti si mai jos la :
`if (await Permission.photos.isGranted) {`

Trebuie putin refactor aici, nu inteleg diferenta intre Permission.photos.status.isGranted si  Permission.photos.isGranted, nu-i acelasi lucru?

2024-12-04 10:35 UTC, ToniVinter commented on lib/app/features/user_settings/application/user_settings_notifier.dart
> +  Future<bool> checkNotificationPermissions() async {
aici ti-ai creeat o metoda care verifica statusul, mai sus in widget folosesti Permission.notification.status;

decide-te la una din ele :))

2024-12-04 10:35 UTC, ToniVinter commented on lib/app/features/user_settings/application/user_settings_notifier.dart
> +  Future<bool> checkNotificationPermissions() async {
poti sterge metoda asta

2024-12-10 07:28 UTC, BeniaminSzilagyi commented on ios/Podfile
Can't access the status of the permissions in the phone settings.

![Screenshot 2024-12-10 at 9 27 18 AM](https://github.com/user-attachments/assets/3b42c575-4904-4464-b6e5-a374f0eaae6f)

2024-12-10 08:00 UTC, ToniVinter approved these changes

2024-12-10 09:03 UTC, merged