Stg 23
OnStageApp/on-stage-app pull request #87
Opened 2024-06-01 21:08 UTC by BeniaminSzilagyi

## Title

## Description

## Screenshots

2024-06-04 15:11 UTC, ToniVinter commented on lib/app/features/event/presentation/widgets/participants_on_tile.dart
> +  final Color borderColor; // Changed to non-nullable Color
extra comm

2024-06-04 15:11 UTC, ToniVinter commented on lib/app/features/event/presentation/widgets/participants_on_tile.dart
> +    this.borderColor = Colors.white, // Default border color
extra comm

2024-06-04 15:13 UTC, ToniVinter commented on lib/app/features/home/presentation/home_screen.dart
> +    // final songs = ref.watch(songsNotifierProvider).songs;
extra comm

2024-06-04 15:15 UTC, ToniVinter commented on lib/app/features/home/presentation/widgets/saved_songs_tiled.dart
> +                style: Theme.of(context).textTheme.titleLarge!.copyWith(
you can use context.textTheme....

2024-06-04 15:15 UTC, ToniVinter commented on lib/app/features/home/presentation/widgets/saved_songs_tiled.dart
> +          const Expanded(child: SizedBox()),
You can use Spacer instead of this

2024-06-04 15:15 UTC, ToniVinter commented on lib/app/features/home/presentation/widgets/saved_songs_tiled.dart
> +              const Expanded(child: SizedBox()),
Spacer()

2024-06-04 15:16 UTC, ToniVinter commented on lib/app/features/home/presentation/widgets/upcoming_event_enhanced.dart
> +                  style: Theme.of(context).textTheme.titleLarge!.copyWith(
context.textTheme

2024-06-04 15:16 UTC, ToniVinter commented on lib/app/features/home/presentation/widgets/upcoming_event_enhanced.dart
> +                  style: Theme.of(context).textTheme.titleSmall!.copyWith(
context.

2024-06-04 15:16 UTC, ToniVinter commented on lib/app/features/home/presentation/widgets/upcoming_event_enhanced.dart
> +                const Expanded(child: SizedBox()),
Spacer

2024-06-04 15:18 UTC, ToniVinter commented on lib/app/features/song/presentation/widgets/stage_search_bar.dart
> +      child: SearchBar(
this one can be a widget

2024-06-04 15:18 UTC, ToniVinter requested changes
quick fixes

2024-06-04 15:33 UTC, avinter-spiffy commented on lib/app/features/event/presentation/widgets/participants_on_tile.dart
> +      width: 118,
this change added a overflow error on the right, width has to be dynamic, not static.

2024-06-04 15:34 UTC, ToniVinter commented on lib/app/features/event/presentation/widgets/participants_on_tile.dart
> +      width: 118,
<img width="1542" alt="image" src="https://github.com/OnStageApp/on-stage-app/assets/41964018/1a72ecee-2a63-435b-bfb2-d582526419e3">

2024-06-04 15:38 UTC, ToniVinter commented
<img width="1150" alt="image" src="https://github.com/OnStageApp/on-stage-app/assets/41964018/15186a15-9a58-4956-a196-26fdd43dbfc5">

Recently Added instead of Upcoming Events

2024-06-04 15:41 UTC, ToniVinter commented on lib/app/features/home/presentation/home_screen.dart
> +                  height: 24,
Icon size is 15, not 24

2024-06-04 15:43 UTC, ToniVinter commented on lib/app/features/home/presentation/home_screen.dart
> +            style: ElevatedButton.styleFrom(
style param has to be above the child widget ( icon: .. )

2024-06-04 15:44 UTC, ToniVinter commented on lib/app/features/home/presentation/home_screen.dart
>                title: 'Duminică seara la elsh',
this title has a different color, here's the design:

<img width="746" alt="image" src="https://github.com/OnStageApp/on-stage-app/assets/41964018/e07f228c-2108-4199-8f38-833191398fad">

2024-06-15 21:01 UTC, BeniaminSzilagyi commented on lib/app/features/song/presentation/widgets/stage_search_bar.dart
> +      child: SearchBar(
meaning?

2024-06-15 21:11 UTC, BeniaminSzilagyi commented on lib/app/features/home/presentation/home_screen.dart
> +                  height: 24,
<img width="361" alt="Screenshot 2024-06-16 at 12 10 48 AM" src="https://github.com/OnStageApp/on-stage-app/assets/40525616/58dcdb6e-65f4-4a7b-8932-5232fc4ea098">

with 15 size

2024-06-15 21:13 UTC, BeniaminSzilagyi commented on lib/app/features/home/presentation/home_screen.dart
> +                  height: 24,
![Screenshot 2024-06-16 at 12 13 10 AM](https://github.com/OnStageApp/on-stage-app/assets/40525616/12d0c466-2a4d-482e-89fb-7fbce65f3d93)

2024-07-04 12:27 UTC, ToniVinter approved these changes

2024-07-04 12:27 UTC, merged